account_id = "56db5c1a91ec01f4b3c7c612d8ebeeef"
name       = "translator-worker"
main       = "src/index.ts"
compatibility_date = "2025-07-31"

# 阻止 Wrangler 把 public/ 认作静态站点 (可选)
assets = ""

[[ai]]
binding             = "AI"          # 与代码里的 env.AI 匹配
experimental_remote = true


# ——— 下面是免费配额 KV ———
[[kv_namespaces]]
binding = "FREE_KV"
id = \"903c0b76289b452b95b4628c340d68ab\"